// Package apitomcp converts declarative REST-API-to-MCP YAML configurations
// into live mcprouter.Backend implementations. A single YAML file describes
// one MCP server with one or more tools; each tool maps an MCP call to an
// HTTP request (requestTemplate) and shapes the response (responseTemplate).
//
// The YAML schema is compatible with github.com/higress-group/openapi-to-mcpserver
// so configs generated by that project's OpenAPI converter can be loaded
// directly.
package apitomcp

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"text/template"
	"time"

	"github.com/godeps/gonacos/pkg/ai/mcprouter"
	"github.com/higress-group/openapi-to-mcpserver/pkg/models"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"gopkg.in/yaml.v3"
)

// Converter turns MCPConfig YAML into Backends.
type Converter struct {
	httpClient *http.Client
	transport  *SafeTransport
}

// NewConverter creates a Converter with the SSRF-safe HTTP client. The
// default client rejects connections to private, loopback, and link-local
// IP addresses so a malicious user-configured URL template cannot reach
// internal services or cloud metadata endpoints. Set AllowPrivate on the
// returned Converter's transport (via [Converter.WithAllowPrivate]) only
// in trusted development environments.
func NewConverter() *Converter {
	transport := NewSafeTransport()
	return &Converter{
		httpClient: transport.HTTPClient(30 * time.Second),
		transport:  transport,
	}
}

// NewConverterFromEnv returns a Converter configured via the
// GONACOS_APITOMCP_ALLOW_PRIVATE environment variable. When set to "true"
// (case-insensitive), the converter permits dials to private, loopback,
// and link-local IPs — use this ONLY in trusted development environments
// where the target MCP server runs on the same host or a private network.
// Production deployments should leave the env var unset so SSRF
// protection stays on.
//
// The env var is read at every call rather than cached at startup so
// operators can toggle it via a config-reload signal that re-reads env
// vars without restarting the process.
func NewConverterFromEnv() *Converter {
	conv := NewConverter()
	if strings.EqualFold(strings.TrimSpace(os.Getenv("GONACOS_APITOMCP_ALLOW_PRIVATE")), "true") {
		conv = conv.WithAllowPrivate()
	}
	return conv
}

// WithAllowPrivate enables private-IP access on the converter's HTTP client.
// Use ONLY in trusted development environments where the target MCP server
// runs on the same host or a private network that the gonacos process must
// reach. Returns the converter for chaining.
func (c *Converter) WithAllowPrivate() *Converter {
	if c.transport != nil {
		c.transport.AllowPrivate = true
		c.httpClient = c.transport.HTTPClient(30 * time.Second)
	}
	return c
}

// WithAllowlist adds hostnames whose private-IP resolutions are permitted
// (bypass the SSRF private-IP check). Use this when a specific internal MCP
// server runs on a private network that the gonacos process must reach.
// Hostnames not in the list still go through the normal SSRF check at dial
// time. Empty list disables the bypass (default). Returns the converter
// for chaining.
func (c *Converter) WithAllowlist(hosts []string) *Converter {
	if c.transport != nil {
		c.transport.Allowlist = hosts
	}
	return c
}

// LoadYAML parses YAML bytes into a MCPConfig. The schema is the higress
// openapi-to-mcpserver schema (server + tools + securitySchemes).
func (c *Converter) LoadYAML(b []byte) (*models.MCPConfig, error) {
	var cfg models.MCPConfig
	if err := yaml.Unmarshal(b, &cfg); err != nil {
		return nil, fmt.Errorf("parse yaml: %w", err)
	}
	if err := validateConfig(&cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// LoadYAMLBytes is an alias for LoadYAML kept for API symmetry with the
// io.Reader-based loader.
func (c *Converter) LoadYAMLBytes(b []byte) (*models.MCPConfig, error) {
	return c.LoadYAML(b)
}

// LoadYAMLReader reads YAML from r and parses it.
func (c *Converter) LoadYAMLReader(r io.Reader) (*models.MCPConfig, error) {
	data, err := io.ReadAll(r)
	if err != nil {
		return nil, fmt.Errorf("read yaml: %w", err)
	}
	return c.LoadYAML(data)
}

// ToBackend converts a MCPConfig into a Backend mounted on the router
// under the server name. Variables are substituted into URL/Header/Body
// templates via Go text/template; the same context also exposes `.args`
// for the tool call arguments and `.response` for the HTTP response body
// in the response template.
func (c *Converter) ToBackend(cfg *models.MCPConfig, vars map[string]string) (mcprouter.Backend, error) {
	if cfg == nil {
		return nil, ErrNilConfig
	}
	name := strings.TrimSpace(cfg.Server.Name)
	if name == "" {
		return nil, ErrMissingServerName
	}
	tools := make([]*models.Tool, 0, len(cfg.Tools))
	for i := range cfg.Tools {
		t := &cfg.Tools[i]
		if strings.TrimSpace(t.Name) == "" {
			return nil, fmt.Errorf("%w: tool at index %d missing name", ErrInvalidConfig, i)
		}
		if strings.TrimSpace(t.RequestTemplate.URL) == "" {
			return nil, fmt.Errorf("%w: tool %q missing requestTemplate.url", ErrInvalidConfig, t.Name)
		}
		tools = append(tools, t)
	}
	if len(tools) == 0 {
		return nil, ErrNoTools
	}
	b := &ApiToMcpBackend{
		name:       name,
		tools:      tools,
		vars:       vars,
		httpClient: c.httpClient,
	}
	return b, nil
}

// ApiToMcpBackend is a mcprouter.Backend that dispatches MCP tool calls
// to HTTP requests described by RequestTemplate and shapes responses via
// ResponseTemplate.
type ApiToMcpBackend struct {
	name       string
	tools      []*models.Tool
	vars       map[string]string
	httpClient *http.Client
}

// Name returns the backend's server name.
func (b *ApiToMcpBackend) Name() string { return b.name }

// ListTools returns the tools advertised by the YAML config, rewrapped
// into the go-sdk Tool type with a best-effort input schema derived from
// the declared Args.
func (b *ApiToMcpBackend) ListTools(_ context.Context) ([]*mcp.Tool, error) {
	out := make([]*mcp.Tool, 0, len(b.tools))
	for _, t := range b.tools {
		tool := &mcp.Tool{
			Name:        t.Name,
			Description: t.Description,
			InputSchema: buildInputSchema(t.Args),
		}
		out = append(out, tool)
	}
	return out, nil
}

// CallTool renders the RequestTemplate, performs the HTTP request, and
// renders the ResponseTemplate with the result.
func (b *ApiToMcpBackend) CallTool(ctx context.Context, name string, args map[string]any) (*mcp.CallToolResult, error) {
	tool := b.findTool(name)
	if tool == nil {
		return nil, fmt.Errorf("%w: %s", mcprouter.ErrMissingToolName, name)
	}
	tmplCtx := map[string]any{
		"args":    args,
		"vars":    b.vars,
		"tool":    map[string]any{"name": tool.Name, "description": tool.Description},
		"request": map[string]any{},
	}
	req, err := buildRequest(ctx, tool, tmplCtx, b.vars)
	if err != nil {
		return nil, err
	}
	resp, err := b.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("http call: %w", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	tmplCtx["response"] = map[string]any{
		"body":       string(body),
		"statusCode": resp.StatusCode,
		"headers":    flattenHeaders(resp.Header),
	}
	out, err := renderResponseTemplate(tool, tmplCtx)
	if err != nil {
		return nil, err
	}
	isError := resp.StatusCode >= 400
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: out},
		},
		IsError: isError,
	}, nil
}

func (b *ApiToMcpBackend) findTool(name string) *models.Tool {
	for _, t := range b.tools {
		if t.Name == name {
			return t
		}
	}
	return nil
}

// buildRequest renders the URL, method, headers, and body templates and
// returns an *http.Request ready for transport.
func buildRequest(ctx context.Context, tool *models.Tool, tmplCtx map[string]any, vars map[string]string) (*http.Request, error) {
	rt := tool.RequestTemplate
	method := strings.TrimSpace(rt.Method)
	if method == "" {
		method = http.MethodGet
	}
	renderedURL, err := renderTemplate("url", rt.URL, tmplCtx)
	if err != nil {
		return nil, fmt.Errorf("render url: %w", err)
	}
	var bodyReader io.Reader
	if strings.TrimSpace(rt.Body) != "" {
		renderedBody, err := renderTemplate("body", rt.Body, tmplCtx)
		if err != nil {
			return nil, fmt.Errorf("render body: %w", err)
		}
		bodyReader = strings.NewReader(renderedBody)
	} else if rt.ArgsToFormBody {
		form := url.Values{}
		for k, v := range toStringMap(args(tmplCtx)) {
			form.Set(k, v)
		}
		bodyReader = strings.NewReader(form.Encode())
	} else if rt.ArgsToJsonBody {
		jsonBytes, _ := json.Marshal(args(tmplCtx))
		bodyReader = bytes.NewReader(jsonBytes)
	}
	req, err := http.NewRequestWithContext(ctx, method, renderedURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	for _, h := range rt.Headers {
		rendered, err := renderTemplate("header."+h.Key, h.Value, tmplCtx)
		if err != nil {
			return nil, fmt.Errorf("render header %s: %w", h.Key, err)
		}
		req.Header.Set(h.Key, rendered)
	}
	if rt.ArgsToJsonBody && bodyReader != nil && req.Header.Get("Content-Type") == "" {
		req.Header.Set("Content-Type", "application/json")
	}
	if rt.ArgsToFormBody && bodyReader != nil && req.Header.Get("Content-Type") == "" {
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	}
	return req, nil
}

// renderResponseTemplate concatenates prependBody, body, and appendBody
// templates and renders them with the request context.
func renderResponseTemplate(tool *models.Tool, tmplCtx map[string]any) (string, error) {
	var b strings.Builder
	if tool.ResponseTemplate.PrependBody != "" {
		out, err := renderTemplate("prependBody", tool.ResponseTemplate.PrependBody, tmplCtx)
		if err != nil {
			return "", fmt.Errorf("render prependBody: %w", err)
		}
		b.WriteString(out)
	}
	if tool.ResponseTemplate.Body != "" {
		out, err := renderTemplate("body", tool.ResponseTemplate.Body, tmplCtx)
		if err != nil {
			return "", fmt.Errorf("render body: %w", err)
		}
		b.WriteString(out)
	}
	if tool.ResponseTemplate.AppendBody != "" {
		out, err := renderTemplate("appendBody", tool.ResponseTemplate.AppendBody, tmplCtx)
		if err != nil {
			return "", fmt.Errorf("render appendBody: %w", err)
		}
		b.WriteString(out)
	}
	if tool.ErrorResponseTemplate != nil && tmplCtx["response"] != nil {
		if resp, ok := tmplCtx["response"].(map[string]any); ok {
			if code, _ := resp["statusCode"].(int); code >= 400 {
				errOut, err := renderTemplate("errorBody", *tool.ErrorResponseTemplate, tmplCtx)
				if err != nil {
					return "", fmt.Errorf("render errorBody: %w", err)
				}
				return errOut, nil
			}
		}
	}
	return b.String(), nil
}

// renderTemplate parses and executes a Go text/template in one shot.
// Templates may reference .args, .vars, .tool, .request, and .response.
func renderTemplate(name, text string, ctx map[string]any) (string, error) {
	if text == "" {
		return "", nil
	}
	tmpl, err := template.New(name).Parse(text)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ctx); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}
	return buf.String(), nil
}

// buildInputSchema derives a JSON-schema object from the declared Args.
func buildInputSchema(args []models.Arg) map[string]any {
	if len(args) == 0 {
		return map[string]any{"type": "object", "properties": map[string]any{}}
	}
	props := map[string]any{}
	required := []string{}
	for _, a := range args {
		t := a.Type
		if t == "" {
			t = "string"
		}
		prop := map[string]any{
			"type":        t,
			"description": a.Description,
		}
		if a.Default != nil {
			prop["default"] = a.Default
		}
		if len(a.Enum) > 0 {
			prop["enum"] = a.Enum
		}
		props[a.Name] = prop
		if a.Required {
			required = append(required, a.Name)
		}
	}
	schema := map[string]any{
		"type":       "object",
		"properties": props,
	}
	if len(required) > 0 {
		schema["required"] = required
	}
	return schema
}

func flattenHeaders(h http.Header) map[string]string {
	out := make(map[string]string, len(h))
	for k, v := range h {
		if len(v) > 0 {
			out[k] = v[0]
		}
	}
	return out
}

func args(ctx map[string]any) map[string]any {
	a, _ := ctx["args"].(map[string]any)
	return a
}

func toStringMap(in map[string]any) map[string]string {
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = fmt.Sprintf("%v", v)
	}
	return out
}

func validateConfig(cfg *models.MCPConfig) error {
	if cfg == nil {
		return ErrNilConfig
	}
	if strings.TrimSpace(cfg.Server.Name) == "" {
		return ErrMissingServerName
	}
	return nil
}

var (
	// ErrNilConfig is returned when a nil config is passed to ToBackend.
	ErrNilConfig = errors.New("apitomcp: config is nil")
	// ErrMissingServerName is returned when the server name is empty.
	ErrMissingServerName = errors.New("apitomcp: server.name is required")
	// ErrNoTools is returned when a config has no tools.
	ErrNoTools = errors.New("apitomcp: no tools configured")
	// ErrInvalidConfig is returned for structural config problems.
	ErrInvalidConfig = errors.New("apitomcp: invalid config")
)
